version: "3"
services:
  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=employeedb
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234

  server:
    depends_on:
      - mysqldb
    image: alluneed
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/employeedb?useSSL=false
    networks:
      - springmysql-net

networks:
  springmysql-net: